[workspace]
members = [".", "examples"]

[package]
name = "starrocks-stream-load"
description = "StarRocks Stream Load SDK for Rust."
version = "1.0.12"
edition = "2024"
# rust-version to follow apache arrow-rs which is 1.85
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/jimmystewpot/starrocks-stream-load"
keywords = ["starrocks", "stream-load", "sdk", "http"]
categories = ["database", "database-implementations", "api-bindings"]
exclude = ["test_data/*"]

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
reqwest = { version = "0.13.4", default-features = false, features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.138" }
bytes = { version = "1.12.1" }
thiserror = { version = "2.0.18" }
tracing = { version = "0.1.41" }
url = { version = "2.5.4" }

[features]
rustls = ["reqwest/rustls"]
native-tls = ["reqwest/native-tls"]

[dev-dependencies]
wiremock = "0.6.5"
criterion = { version = "0.8.2", features = ["async_tokio"] }

[[bench]]
name = "load_bench"
harness = false

[profile.release]
lto = "thin"
debug = true

[profile.dist]
inherits = "release"
lto = "thin"